import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import UserProvider from '@/context/userProvider'
import BusinessProvider from '@/context/businessProvider'
import ProductsProvider from '@/context/productsProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mis Pedidos - business',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ProductsProvider>
      <BusinessProvider>
      <UserProvider>
      <body className={inter.className}>
        <Navbar navigation={[
          { name: 'Dashboard', ref: '/dashboard' },
          { name: 'Pedidos', ref: '/orders' },
          { name: 'Productos', ref: '/products' },
        ]}/>
        {children}
        </body>
      </UserProvider>
      </BusinessProvider>
      </ProductsProvider>
    </html>
  )
}
